# Configuration Data Source
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lesson2_hw
    username: postgres
    password: 123456
  jpa:
    open-in-view: true

  #Eurika properties
eureka:
  client.service-url:
    defaultZone: http://192.168.1.35:8761/eureka
  instance:
    prefer-ip-address: true